name: 'Test'
on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Test
      run: |
        npm ci
        npm run build
        npm run snapshots
      env: 
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        PERCY_COMMIT: ${{ github.sha }}
        PERCY_BRANCH: ${{ github.ref }}
        PERCY_TARGET_BRANCH: ${{ github.base_ref }}
        PERCY_TARGET_COMMIT: ${{ github.head_ref }}

