name: 'Test'
on: 
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Test
      run: |
        npm ci
        npm run build
        npm run snapshots
      env: 
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
