name: 'Lint | Test'
description: 'Lint and test for pull requests'
on: 
  pull_request:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: ESLint checks
      uses: gimenete/eslint-action@1.0

    - name: Test
      run: |
        npm ci
        npm run snapshots
      env: 
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

